### List tasks
GET http://localhost:3001/tasks

### Get task by ID
GET http://localhost:3001/tasks/3

### Create task
POST http://localhost:3001/tasks
Content-Type: application/json

{
    "title":"Another task",
    "completed":false
}